---
- name: Limpa o arquivo /etc/hosts
  shell: echo '' > /etc/hosts
  tags: hosts

- name: Configuracao do arquivo /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }} {{ item.fqdn }} {{ item.alias }}"
  with_items:
    - { ip: '127.0.0.1', fqdn: 'localhost.localdomain', alias: 'localhost' }
    - { ip: '10.0.0.10', fqdn: 'controller.openstack.local', alias: 'controller' }
    - { ip: '10.0.0.11', fqdn: 'compute.openstack.local', alias: 'compute' }
    - { ip: '10.0.0.12', fqdn: 'storage.openstack.local', alias: 'storage' }
    - { ip: '10.0.0.13', fqdn: 'share.openstack.local', alias: 'share' }
    - { ip: '10.0.0.14', fqdn: 'object1.openstack.local', alias: 'object1' }
    - { ip: '10.0.0.15', fqdn: 'object2.openstack.local', alias: 'object2' }
  tags: hosts
